import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  
  // 1. USERS (Synced with Clerk)
  users: defineTable({
    clerkId: v.string(), // The external ID from Clerk
    email: v.string(),
    name: v.optional(v.string()),
    avatar: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_clerk_id", ["clerkId"]),

  // 2. TEAMS (Organizations)
  teams: defineTable({
    name: v.string(),
    slug: v.string(), // e.g. "wego-corp"
    plan: v.union(v.literal("free"), v.literal("pro"), v.literal("enterprise")),
    stripeCustomerId: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),

  // 3. TEAM MEMBERS (Linking Users to Teams)
  team_members: defineTable({
    teamId: v.id("teams"),
    userId: v.id("users"),
    role: v.union(v.literal("owner"), v.literal("admin"), v.literal("viewer")),
    status: v.union(v.literal("active"), v.literal("invited")),
    invitedEmail: v.optional(v.string()), // If user hasn't signed up yet
    joinedAt: v.number(),
  })
  .index("by_team", ["teamId"])
  .index("by_user", ["userId"])
  .index("by_team_user", ["teamId", "userId"]), // Composite index for permission checks

  // 4. PROJECTS (Belong to a Team)
  projects: defineTable({
    teamId: v.id("teams"),
    name: v.string(),
    url: v.string(),
    // API Keys (In real app, hash the secret key!)
    publishableKey: v.string(), 
    secretKey: v.string(),
    // Feature Toggles (From your Settings Page)
    settings: v.object({
        sessionReplay: v.boolean(),
        scanMode: v.union(v.literal("diff"), v.literal("full")),
        maskPrivacy: v.boolean(),
    }),
    createdAt: v.number(),
  }).index("by_team", ["teamId"]),

  // 5. ANALYTICS (Batched & Lightweight)
  analytics_sessions: defineTable({
    projectId: v.id("projects"),
    visitorId: v.string(), // Fingerprint
    country: v.optional(v.string()),
    device: v.string(),
    browser: v.string(),
    startedAt: v.number(),
    lastActiveAt: v.number(),
    duration: v.number(),
    eventsCount: v.number(),
    // If replay enabled, we store the big JSON blob here (or link to file storage)
    replayData: v.optional(v.any()), // JSON of DOM mutation events
  }).index("by_project", ["projectId"]),

  analytics_events: defineTable({
    projectId: v.id("projects"),
    sessionId: v.id("analytics_sessions"),
    type: v.string(), // "pageview", "click", "rage_click"
    path: v.string(),
    x: v.optional(v.number()), // For heatmaps
    y: v.optional(v.number()), 
    createdAt: v.number(),
  }).index("by_project_type", ["projectId", "type"]),

  // 6. CODE HEALTH (GitHub Webhooks)
  code_audits: defineTable({
    projectId: v.id("projects"),
    commitHash: v.string(),
    branch: v.string(),
    author: v.string(),
    message: v.string(),
    riskScore: v.number(), // 0-100
    aiSummary: v.string(), // Generated by Agent
    issues: v.array(v.object({
        severity: v.string(),
        file: v.string(),
        line: v.number(),
        description: v.string(),
        suggestion: v.optional(v.string()),
    })),
    createdAt: v.number(),
  }).index("by_project", ["projectId"]),

  // 7. SEO SCANS
  seo_scans: defineTable({
    projectId: v.id("projects"),
    url: v.string(),
    strategy: v.union(v.literal("mobile"), v.literal("desktop")),
    scores: v.object({
        performance: v.number(),
        accessibility: v.number(),
        seo: v.number(),
        bestPractices: v.number(),
    }),
    coreWebVitals: v.any(), // JSON from Google
    createdAt: v.number(),
  }).index("by_project", ["projectId"]),
});